tap "caskroom/fonts"


brew "exercism"
brew "git"
brew "imagemagick"
brew "python"
brew "ruby"
brew "sqlite"
brew "vim"
brew "yarn"
brew "zsh"
brew "zsh-syntax-highlighting"

# Casks
cask "github"
cask "1password"
cask "alfred"
cask "caffeine"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "postman"
cask "transmission"
cask "visual-studio-code"
cask "spotify"
cask "nordvpn"
cask "parallels"