tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "git"
brew "python"
brew "ruby"
brew "sqlite"
brew "vim"
brew "yarn"
brew 'nvm'

# Casks
cask "github"
cask "obsidian"
cask "mongodb-compass"
cask "raycast"
cask "1password"
# cask "alfred"
# cask "backblaze"
# cask "caffeine"
cask "google-chrome"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
# cask "hyper"
cask "iina"
cask "iterm2"
cask "postman"
cask "transmission"
cask "visual-studio-code"
cask "spotify"
#cask "nordvpn"
cask "balenaetcher"
cask "zoomus"
cask "obs"
cask "rectangle"
